linters:
  enable-all: false
  disable-all: true
  fast: false
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - exhaustive
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - whitespace
    - gofumpt

  exclude_paths:
    - "vendor"
    - "mocks"
    - "gen"
    - "*.mock.go" 
    - "*.gen.go"

run:
 concurrency: 4
 timeout: 5m
 tests: false
