version: "3"

vars:
  SERVICE_NAME: upload

includes:
  builds: ../../scripts/tasksfiles/build.Taskfile.yml
  linters: ../../scripts/tasksfiles/lint.Taskfile.yml
  tests: ../../scripts/tasksfiles/test.Taskfile.yml

tasks:
  default:
    cmds:
      - task: lint
      - task: tests:test

  lint:
    cmds:
      - task: linters:go-lint
